### ISSUE TITLE
Problems with ping

### ISSUE THREAD

**Issue by bewee** [mozilla-iot/wake-on-lan-adapter#8]
The checkPing setting does not work for me. My computer gets monitored as turned off all the time.

Even worse, enabling this setting seems to mess up my whole gateway: As a result, many other add-ons fail to start correctly:

```
thing-url-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
tuya-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
frontier-silicon-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
```

I have no idea why this is happening and wasn't able to reproduce the problem in a docker container. However, it also appears on a freshly setup raspberry pi.

**Comment by mrstegeman** [comment]
Are there any errors popping up before those messages? Seems like those are probably just a side effect of some other crash.

**Comment by bewee** [comment]
Normal log on startup:
```
2020-11-02 09:43:21.704 INFO   : Opening database: /home/pi/.mozilla-iot/log/logs.sqlite3
2020-11-02 09:43:24.258 INFO   : DNS config is: gateway
2020-11-02 09:43:24.264 INFO   : Service Discovery: changing profile - local domain is now: gateway
2020-11-02 09:43:28.774 INFO   : Service Discovery: state changed to: true
2020-11-02 09:43:28.823 INFO   : HTTPS server listening on port 4443
2020-11-02 09:43:28.826 INFO   : Redirector listening on port 8080
2020-11-02 09:43:35.647 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:43:35.812 INFO   : Loading add-on: frontier-silicon-adapter
2020-11-02 09:43:35.828 INFO   : Loading add-on: wake-on-lan-adapter
2020-11-02 09:43:35.833 INFO   : Loading add-on: tuya-adapter
2020-11-02 09:59:21.200 INFO   : Loading add-on: thing-url-adapter
2020-11-02 09:43:37.211 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:43:37.457 INFO   : PageKite connected!
2020-11-02 09:43:37.470 INFO   : Starting certificate renewal.
2020-11-02 09:43:37.550 INFO   : Certificate not yet due for renewal.
2020-11-02 09:43:40.339 INFO   : Checking for add-on updates...
2020-11-02 09:43:41.366 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:43:41.375 INFO   : tuya-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:43:41.400 INFO   : frontier-silicon-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:43:41.631 INFO   : wake-on-lan-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:43:42.173 INFO   : Not updating frontier-silicon-adapter since a .git directory was detected
2020-11-02 09:43:42.177 INFO   : Not updating hp-cp1515n-adapter since a .git directory was detected
2020-11-02 09:43:42.210 INFO   : Not updating unipotsdam-dorm-zim-internet-statistics-adapter since a .git directory was detected
2020-11-02 09:43:42.214 INFO   : Finished updating add-ons
2020-11-02 09:43:42.313 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:43:43.316 INFO   : thing-url-adapter: Loading add-on thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2020-11-02 09:43:43.327 INFO   : tuya-adapter: Loading add-on tuya-adapter from /home/pi/.mozilla-iot/addons/tuya-adapter
2020-11-02 09:43:43.525 INFO   : frontier-silicon-adapter: Loading add-on frontier-silicon-adapter from /home/pi/.mozilla-iot/addons/frontier-silicon-adapter
2020-11-02 09:43:43.746 INFO   : wake-on-lan-adapter: Loading add-on wake-on-lan-adapter from /home/pi/.mozilla-iot/addons/wake-on-lan-adapter
2020-11-02 09:43:43.891 INFO   : thing-url-adapter: Starting mDNS discovery
2020-11-02 09:43:45.855 INFO   : tuya-adapter: setCachedValueAndNotify for property on from undefined to false for tuya-35745080840d8e7fea1f
...
2020-11-02 09:43:45.953 INFO   : getValue for property on for: Benedikts Lampe returning false
2020-11-02 09:43:45.955 INFO   : getValue for property mode for: Benedikts Lampe returning White
2020-11-02 09:43:45.958 INFO   : getValue for property brightness for: Benedikts Lampe returning 100
2020-11-02 09:43:45.961 INFO   : getValue for property lighttemperature for: Benedikts Lampe returning 6500
2020-11-02 09:43:48.957 INFO   : tuya-adapter: setCachedValueAndNotify for property on from undefined to false for tuya-357450802cf432ba5b52
...
2020-11-02 09:43:49.083 INFO   : getValue for property on for: Nils' Lampe returning false
2020-11-02 09:43:49.086 INFO   : getValue for property mode for: Nils' Lampe returning White
2020-11-02 09:43:49.089 INFO   : getValue for property brightness for: Nils' Lampe returning 100
2020-11-02 09:43:49.091 INFO   : getValue for property lighttemperature for: Nils' Lampe returning 2500
2020-11-02 09:44:48.331 INFO   : frontier-silicon-adapter: Thing added frontier-silicon-00226186A3F4
2020-11-02 09:44:48.336 INFO   : frontier-silicon-adapter: Thing saved later frontier-silicon-00226186A3F4
2020-11-02 09:44:48.540 INFO   : frontier-silicon-adapter: frontier-silicon-00226186A3F4 Connected!
2020-11-02 09:44:48.544 INFO   : frontier-silicon-adapter: frontier-silicon-00226186A3F4 Updating all properties!
2020-11-02 09:44:48.742 INFO   : frontier-silicon-adapter: setCachedValueAndNotify for property netremote.sys.power from undefined to false for frontier-silicon-00226186A3F4
...
```

This happens when I enable the checkPing setting:

```
2020-11-02 09:45:28.264 INFO   : wake-on-lan-adapter: Adapter: WakeOnLanAdapter unloaded
2020-11-02 09:45:32.379 INFO   : Loading add-on: wake-on-lan-adapter
2020-11-02 09:45:35.526 INFO   : wake-on-lan-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:45:37.004 INFO   : wake-on-lan-adapter: Loading add-on wake-on-lan-adapter from /home/pi/.mozilla-iot/addons/wake-on-lan-adapter
2020-11-02 09:45:48.840 INFO   : frontier-silicon-adapter: Unhandled Rejection
2020-11-02 09:45:48.852 ERROR  : frontier-silicon-adapter: { FetchError: request to http://192.168.3.2/fsapi/GET_NOTIFIES/?pin=1234&sid=1007741481 failed, reason: connect EHOSTUNREACH 192.168.3.2:80
2020-11-02 09:45:48.857 ERROR  : frontier-silicon-adapter:     at ClientRequest.<anonymous> (/home/pi/.mozilla-iot/addons/frontier-silicon-adapter/node_modules/node-fetch/lib/index.js:1461:11)
2020-11-02 09:45:48.861 ERROR  : frontier-silicon-adapter:     at ClientRequest.emit (events.js:198:13)
2020-11-02 09:45:48.866 ERROR  : frontier-silicon-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-11-02 09:45:48.870 ERROR  : frontier-silicon-adapter:     at Socket.emit (events.js:198:13)
2020-11-02 09:45:48.873 ERROR  : frontier-silicon-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-11-02 09:45:48.878 ERROR  : frontier-silicon-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-11-02 09:45:48.885 ERROR  : frontier-silicon-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-11-02 09:45:48.889 ERROR  : frontier-silicon-adapter:   message:
2020-11-02 09:45:48.893 ERROR  : frontier-silicon-adapter:    'request to http://192.168.3.2/fsapi/GET_NOTIFIES/?pin=1234&sid=1007741481 failed, reason: connect EHOSTUNREACH 192.168.3.2:80',
2020-11-02 09:45:48.896 ERROR  : frontier-silicon-adapter:   type: 'system',
2020-11-02 09:45:48.908 ERROR  : frontier-silicon-adapter:   errno: 'EHOSTUNREACH',
2020-11-02 09:45:48.910 ERROR  : frontier-silicon-adapter:   code: 'EHOSTUNREACH' }
2020-11-02 09:45:51.017 ERROR  : thing-url-adapter: events.js:174
2020-11-02 09:45:51.021 ERROR  : thing-url-adapter:       throw er; // Unhandled 'error' event
2020-11-02 09:45:51.024 ERROR  : thing-url-adapter:       ^
2020-11-02 09:45:51.026 ERROR  : thing-url-adapter:
2020-11-02 09:45:51.029 ERROR  : thing-url-adapter: Error: send EINVAL 224.0.0.251:5353
2020-11-02 09:45:51.031 ERROR  : thing-url-adapter:     at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
2020-11-02 09:45:51.034 ERROR  : thing-url-adapter: Emitted 'error' event at:
2020-11-02 09:45:51.038 ERROR  : thing-url-adapter:     at Browser._onError (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/Browser.js:146:8)
2020-11-02 09:45:51.040 ERROR  : thing-url-adapter:     at Object.onceWrapper (events.js:286:20)
2020-11-02 09:45:51.043 ERROR  : thing-url-adapter:     at NetworkInterface.emit (events.js:203:15)
2020-11-02 09:45:51.045 ERROR  : thing-url-adapter:     at NetworkInterface._onError (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/NetworkInterface.js:438:8)
2020-11-02 09:45:51.048 ERROR  : thing-url-adapter:     at SendWrap.callback (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/NetworkInterface.js:393:50)
2020-11-02 09:45:51.051 ERROR  : thing-url-adapter:     at SendWrap.afterSend [as oncomplete] (dgram.js:472:8)
2020-11-02 09:45:51.058 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 0
2020-11-02 09:45:56.126 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:46:32.065 ERROR  : thing-url-adapter: events.js:174
2020-11-02 09:46:32.140 ERROR  : thing-url-adapter:       throw er; // Unhandled 'error' event
2020-11-02 09:46:32.144 ERROR  : thing-url-adapter:       ^
2020-11-02 09:46:32.210 ERROR  : thing-url-adapter:
2020-11-02 09:46:32.214 ERROR  : thing-url-adapter: Error: connect ETIMEDOUT 127.0.0.1:9500
2020-11-02 09:46:32.217 ERROR  : thing-url-adapter:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-11-02 09:46:32.219 ERROR  : thing-url-adapter: Emitted 'error' event at:
2020-11-02 09:46:32.222 ERROR  : thing-url-adapter:     at ClientRequest.req.on (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/websocket.js:555:15)
2020-11-02 09:46:32.224 ERROR  : thing-url-adapter:     at ClientRequest.emit (events.js:198:13)
2020-11-02 09:46:32.226 ERROR  : thing-url-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-11-02 09:46:32.229 ERROR  : thing-url-adapter:     at Socket.emit (events.js:198:13)
2020-11-02 09:46:32.231 ERROR  : thing-url-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-11-02 09:46:32.233 ERROR  : thing-url-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-11-02 09:46:32.235 ERROR  : thing-url-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-11-02 09:46:32.241 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 1000
2020-11-02 09:46:43.175 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:47:17.937 ERROR  : thing-url-adapter: events.js:174
2020-11-02 09:47:17.945 ERROR  : thing-url-adapter:       throw er; // Unhandled 'error' event
2020-11-02 09:47:17.949 ERROR  : thing-url-adapter:       ^
2020-11-02 09:47:17.953 ERROR  : thing-url-adapter:
2020-11-02 09:47:17.958 ERROR  : thing-url-adapter: Error: connect ETIMEDOUT 127.0.0.1:9500
2020-11-02 09:47:17.962 ERROR  : thing-url-adapter:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-11-02 09:47:17.966 ERROR  : thing-url-adapter: Emitted 'error' event at:
2020-11-02 09:47:17.970 ERROR  : thing-url-adapter:     at ClientRequest.req.on (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/websocket.js:555:15)
2020-11-02 09:47:17.974 ERROR  : thing-url-adapter:     at ClientRequest.emit (events.js:198:13)
2020-11-02 09:47:17.977 ERROR  : thing-url-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-11-02 09:47:17.980 ERROR  : thing-url-adapter:     at Socket.emit (events.js:198:13)
2020-11-02 09:47:17.998 ERROR  : thing-url-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-11-02 09:47:18.000 ERROR  : thing-url-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-11-02 09:47:18.003 ERROR  : thing-url-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-11-02 09:47:18.009 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 2000
2020-11-02 09:47:23.268 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:47:24.799 INFO   : thing-url-adapter: Loading add-on thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2020-11-02 09:47:25.219 INFO   : thing-url-adapter: Starting mDNS discovery
2020-11-02 09:47:32.367 INFO   : getValue for property netremote.play.repeat for: Teufel Radio 3sixty returning false
2020-11-02 09:47:32.371 INFO   : getValue for property on for: DESKTOP-JCG2H8C.fritz.box returning false
2020-11-02 09:48:28.424 ERROR  : thing-url-adapter: events.js:174
2020-11-02 09:48:28.427 ERROR  : thing-url-adapter:       throw er; // Unhandled 'error' event
2020-11-02 09:48:28.429 ERROR  : thing-url-adapter:       ^
2020-11-02 09:48:28.431 ERROR  : thing-url-adapter:
2020-11-02 09:48:28.433 ERROR  : thing-url-adapter: Error: send EINVAL 224.0.0.251:5353
2020-11-02 09:48:28.435 ERROR  : thing-url-adapter:     at SendWrap.afterSend [as oncomplete] (dgram.js:467:11)
2020-11-02 09:48:28.437 ERROR  : thing-url-adapter: Emitted 'error' event at:
2020-11-02 09:48:28.439 ERROR  : thing-url-adapter:     at Browser._onError (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/Browser.js:146:8)
2020-11-02 09:48:28.442 ERROR  : thing-url-adapter:     at Object.onceWrapper (events.js:286:20)
2020-11-02 09:48:28.444 ERROR  : thing-url-adapter:     at NetworkInterface.emit (events.js:203:15)
2020-11-02 09:48:28.446 ERROR  : thing-url-adapter:     at NetworkInterface._onError (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/NetworkInterface.js:438:8)
2020-11-02 09:48:28.449 ERROR  : thing-url-adapter:     at SendWrap.callback (/home/pi/.mozilla-iot/addons/thing-url-adapter/node_modules/dnssd/lib/NetworkInterface.js:393:50)
2020-11-02 09:48:28.451 ERROR  : thing-url-adapter:     at SendWrap.afterSend [as oncomplete] (dgram.js:472:8)
2020-11-02 09:48:28.459 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 0
2020-11-02 09:48:35.811 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:49:12.810 ERROR  : thing-url-adapter: events.js:174
2020-11-02 09:49:12.813 ERROR  : thing-url-adapter:       throw er; // Unhandled 'error' event
2020-11-02 09:49:12.816 ERROR  : thing-url-adapter:       ^
2020-11-02 09:49:12.819 ERROR  : thing-url-adapter:
2020-11-02 09:49:12.822 ERROR  : thing-url-adapter: Error: connect ETIMEDOUT 127.0.0.1:9500
2020-11-02 09:49:12.825 ERROR  : thing-url-adapter:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-11-02 09:49:12.828 ERROR  : thing-url-adapter: Emitted 'error' event at:
2020-11-02 09:49:12.831 ERROR  : thing-url-adapter:     at ClientRequest.req.on (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/node_modules/ws/lib/websocket.js:555:15)
2020-11-02 09:49:12.850 ERROR  : thing-url-adapter:     at ClientRequest.emit (events.js:198:13)
2020-11-02 09:49:12.853 ERROR  : thing-url-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-11-02 09:49:12.855 ERROR  : thing-url-adapter:     at Socket.emit (events.js:198:13)
2020-11-02 09:49:12.858 ERROR  : thing-url-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-11-02 09:49:12.860 ERROR  : thing-url-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-11-02 09:49:12.863 ERROR  : thing-url-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-11-02 09:49:12.929 INFO   : Plugin: thing-url-adapter died, code = 1 restarting after 1000
2020-11-02 09:49:21.806 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:49:40.229 INFO   : thing-url-adapter: Loading add-on thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2020-11-02 09:49:40.614 INFO   : thing-url-adapter: Starting mDNS discovery
... (thing-url-adapter continues to cycle through exactly the same errors)
```

When I now restart the gateway service, the log looks like this:
```
2020-11-02 09:59:05.674 INFO   : Opening database: /home/pi/.mozilla-iot/log/logs.sqlite3
2020-11-02 09:59:08.261 INFO   : DNS config is: gateway
2020-11-02 09:59:08.266 INFO   : Service Discovery: changing profile - local domain is now: gateway
2020-11-02 09:59:12.910 INFO   : Service Discovery: state changed to: true
2020-11-02 09:59:12.959 INFO   : HTTPS server listening on port 4443
2020-11-02 09:59:12.962 INFO   : Redirector listening on port 8080
2020-11-02 09:59:20.132 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:59:20.292 INFO   : Loading add-on: wake-on-lan-adapter
2020-11-02 09:59:21.171 INFO   : Loading add-on: tuya-adapter
2020-11-02 09:59:21.196 INFO   : Loading add-on: frontier-silicon-adapter
2020-11-02 09:59:21.200 INFO   : Loading add-on: thing-url-adapter
2020-11-02 09:59:21.687 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:59:22.155 INFO   : PageKite connected!
2020-11-02 09:59:22.166 INFO   : Starting certificate renewal.
2020-11-02 09:59:22.338 INFO   : Certificate not yet due for renewal.
2020-11-02 09:59:24.522 INFO   : Checking for add-on updates...
2020-11-02 09:59:25.604 INFO   : tuya-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:59:25.609 INFO   : wake-on-lan-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:59:25.757 INFO   : frontier-silicon-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:59:25.982 INFO   : thing-url-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-11-02 09:59:26.192 INFO   : Not updating frontier-silicon-adapter since a .git directory was detected
2020-11-02 09:59:26.195 INFO   : Not updating hp-cp1515n-adapter since a .git directory was detected
2020-11-02 09:59:26.222 INFO   : Not updating unipotsdam-dorm-zim-internet-statistics-adapter since a .git directory was detected
2020-11-02 09:59:26.227 INFO   : Finished updating add-ons
2020-11-02 09:59:26.320 ERROR  : Failed to get property netremote.sys.power: getProperty: device: frontier-silicon-00226186A3F4 not found.
...
2020-11-02 09:59:27.948 INFO   : tuya-adapter: Loading add-on tuya-adapter from /home/pi/.mozilla-iot/addons/tuya-adapter
2020-11-02 09:59:27.978 INFO   : wake-on-lan-adapter: Loading add-on wake-on-lan-adapter from /home/pi/.mozilla-iot/addons/wake-on-lan-adapter
2020-11-02 09:59:28.010 INFO   : frontier-silicon-adapter: Loading add-on frontier-silicon-adapter from /home/pi/.mozilla-iot/addons/frontier-silicon-adapter
2020-11-02 09:59:28.044 INFO   : thing-url-adapter: Loading add-on thing-url-adapter from /home/pi/.mozilla-iot/addons/thing-url-adapter
2020-11-02 09:59:29.035 INFO   : tuya-adapter: setCachedValueAndNotify for property on from undefined to false for tuya-357450802cf432ba5b52
...
2020-11-02 09:59:38.557 INFO   : tuya-adapter: Unhandled Rejection
2020-11-02 09:59:38.565 ERROR  : tuya-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 09:59:38.574 ERROR  : thing-url-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 09:59:38.616 ERROR  : error running jwt middleware Error: SQLITE_BUSY: database is locked
2020-11-02 09:59:38.640 ERROR  : Error: SQLITE_BUSY: database is locked
2020-11-02 09:59:40.180 ERROR  : frontier-silicon-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 09:59:49.344 INFO   : tuya-adapter: Unhandled Rejection
2020-11-02 09:59:49.350 ERROR  : tuya-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 10:00:13.515 ERROR  : error running jwt middleware Error: SQLITE_BUSY: database is locked
2020-11-02 10:00:13.533 ERROR  : error running jwt middleware Error: SQLITE_BUSY: database is locked
2020-11-02 10:00:25.977 INFO   : getValue for property on for: Nils' Lampe returning false
2020-11-02 10:00:25.980 INFO   : getValue for property mode for: Nils' Lampe returning White
2020-11-02 10:00:25.983 INFO   : getValue for property brightness for: Nils' Lampe returning 100
2020-11-02 10:00:25.986 INFO   : getValue for property lighttemperature for: Nils' Lampe returning 2500
2020-11-02 10:00:26.061 INFO   : tuya-adapter: Unhandled Rejection
2020-11-02 10:00:26.064 INFO   : tuya-adapter: Unhandled Rejection
2020-11-02 10:00:26.092 ERROR  : tuya-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 10:00:26.096 ERROR  : tuya-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
2020-11-02 10:00:26.104 ERROR  : Error: SQLITE_BUSY: database is locked
2020-11-02 10:00:26.106 ERROR  : Error: SQLITE_BUSY: database is locked
```

With a service restart as well as without, my tuya and frontier-silicon devices no longer work. The ping property of my PC stays turned off although it's running.

Edit: Turns out my tuya light is still connected and controllable, it just takes like 30 seconds until my commands are received by the light. The frontier-silicon however is disconnected and not controllable.

**Comment by mrstegeman** [comment]
Honestly not sure what's going on. I'm unable to reproduce on my RPi or my MacBook.
